// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eympxjimldhplotitshq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5bXB4amltbGRocGxvdGl0c2hxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2MDE5MzYsImV4cCI6MjA2NTE3NzkzNn0.rF2KBk5ioAyEfw0J-FXFtMIv_vlokv5QjNumlaYJR_s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);